meta_product_name: "The Darche Side"
meta_title: "The Darche Side - conseil en stratégies marketing, communication et digital"
meta_description: "The Darche Side accompagne entrepreneurs et jeunes marques dans leurs problématiques marketing, image de marque et stratégies digitales."
meta_image: "logo.png" # should exist in `app/assets/images/`
